<a href="https://colab.research.google.com/github/jorgewellison/classifiers-tcc/blob/main/Pre-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importação das bibliotecas**

In [140]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

In [3]:
pd.set_option('display.max_rows', 50)

**Tratamento dos indicadores do IDHM**

In [141]:
atlas = pd.read_excel("/content/drive/My Drive/Colab Notebooks/covid-idhm/atlas2013_dadosbrutos_pt.xlsx", sheet_name=1, 
          usecols=['ANO', 'UF', 'Codmun7', 'Município', 'ESPVIDA', 'FECTOT', 'MORT1', 'SOBRE60', 'T_ENV', 'E_ANOSESTUDO', 'T_ANALF11A14', 'T_ANALF25M', 'T_ATRASO_0_BASICO', 'T_ATRASO_2_BASICO', 'T_FLPRE', 'T_FLSUPER', 'T_FREQSUPER1517', 'T_SUPER25M', 'T_MED25M', 'GINI', 'PIND', 'PINDCRI', 'PMPOB', 'PMPOBCRI', 'RDPC', 'CPR', 'EMP', 'P_AGRO', 'P_COM', 'P_CONSTR', 'P_EXTR', 'P_FORMAL', 'P_FUND', 'P_MED', 'P_SERV', 'P_SIUP', 'P_SUPER', 'T_DES2529', 'TRABCC', 'TRABPUB', 'TRABSC', 'T_AGUA', 'T_BANAGUA', 'T_DENS', 'T_LIXO', 'T_LUZ', 'AGUA_ESGOTO', 'PAREDE', 'T_CRIFUNDIN_TODOS', 'T_FORA4A5', 'T_FORA6A14', 'T_FUNDIN_TODOS', 'T_FUNDIN_TODOS_MMEIO', 'T_FUNDIN18MINF', 'T_M10A14CF', 'T_M15A17CF', 'T_MULCHEFEFIF014', 'T_NESTUDA_NTRAB_MMEIO', 'T_OCUPDESLOC_1', 'T_RMAXIDOSO', 'T_SLUZ', 'HOMEMTOT', 'MULHERTOT', 'pesoRUR', 'pesotot', 'pesourb', 'POP', 'IDHM', 'IDHM_E', 'IDHM_L', 'IDHM_R'], 
          dtype={'UF': str}).rename(columns={'ESPVIDA': 'expec_vida', 'FECTOT': 'taxa_fecund', 'SOBRE60': '%sobreviver_60a', 'T_ENV': 'taxa_envelh', 'E_ANOSESTUDO': 'expec_anos_estudo_18'})
atlasbr = atlas.loc[(atlas['ANO'] == 2010)]

In [142]:
atlasbr.head()

ANO  UF  Codmun7              Município  ...   IDHM  IDHM_E  IDHM_L  IDHM_R
11130  2010  11  1100015  ALTA FLORESTA D'OESTE  ...  0.641   0.526   0.763   0.657
11131  2010  11  1100023              ARIQUEMES  ...  0.702   0.600   0.806   0.716
11132  2010  11  1100031                 CABIXI  ...  0.650   0.559   0.757   0.650
11133  2010  11  1100049                 CACOAL  ...  0.718   0.620   0.821   0.727
11134  2010  11  1100056             CEREJEIRAS  ...  0.692   0.602   0.799   0.688

[5 rows x 71 columns]

**Substituição dos valores nulos**

In [143]:
base = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/covid19-setembro.csv") 
base.head()

epidemiological_week        date  ...  is_last is_repeated
0                    40  2020-09-27  ...    False        True
1                    40  2020-09-27  ...    False        True
2                    40  2020-09-27  ...    False        True
3                    40  2020-09-27  ...    False        True
4                    40  2020-09-27  ...    False        True

[5 rows x 16 columns]

In [144]:
base.isnull().sum()

epidemiological_week                              0
date                                              0
order_for_place                                   0
state                                             0
city                                              0
city_ibge_code                                   19
place_type                                        0
last_available_confirmed                          0
last_available_confirmed_per_100k_inhabitants    22
new_confirmed                                     0
last_available_deaths                             0
new_deaths                                        0
last_available_death_rate                         0
estimated_population_2019                        19
is_last                                           0
is_repeated                                       0
dtype: int64

In [145]:
pd.isnull(base['last_available_confirmed_per_100k_inhabitants'])
base.loc[pd.isnull(base['last_available_confirmed_per_100k_inhabitants'])]

epidemiological_week        date  ...  is_last is_repeated
57                      40  2020-09-27  ...    False        True
367                     40  2020-09-27  ...    False       False
698                     40  2020-09-27  ...    False       False
807                     40  2020-09-27  ...     True       False
841                     40  2020-09-27  ...    False        True
994                     40  2020-09-27  ...     True       False
1695                    40  2020-09-27  ...     True       False
2326                    40  2020-09-27  ...    False        True
2473                    40  2020-09-27  ...    False       False
2650                    40  2020-09-27  ...    False       False
2865                    40  2020-09-27  ...     True       False
3346                    40  2020-09-27  ...    False        True
3384                    40  2020-09-27  ...    False        True
3626                    40  2020-09-27  ...    False        True
3740                    40  2020-09-27  ...    False        True
3879                    40  2020-09-27  ...    False        True
3918                    40  2020-09-27  ...    False        True
4025                    40  2020-09-27  ...     True       False
4100                    40  2020-09-27  ...     True       False
4131                    40  2020-09-27  ...     True       False
4539                    40  2020-09-27  ...    False        True
5032                    40  2020-09-27  ...    False        True

[22 rows x 16 columns]

In [146]:
base = base.drop([57, 367, 698, 807, 841, 994, 1695, 2326, 2473, 2650, 2865, 3346, 3626, 3740, 3879, 3918, 4131, 4539, 5032])

**Remodelando o dataframe dos casos de covid**

In [147]:
cols = list(base.columns.values)
df = base[['city_ibge_code', 'estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants']]
df.fillna(0,inplace=True)
df.isnull().sum()

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


city_ibge_code                                   0
estimated_population_2019                        0
last_available_confirmed_per_100k_inhabitants    0
dtype: int64

In [148]:
base_mort = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/cases-brazil-cities.csv", usecols=['ibgeID', 'deaths_per_100k_inhabitants'])
base_mort.head()

ibgeID  deaths_per_100k_inhabitants
0  5200050                     79.79027
1  3100104                     14.30820
2  5200100                     54.88474
3  1500107                     71.02183
4  3100203                      8.60696

**Junção da tabela de métricas de indicadores do IDHM (Atlas) + dataFrame covid**

In [149]:
idhmcovid = pd.merge(atlasbr, df, left_on="Codmun7", right_on="city_ibge_code", how="left")
idhmcovid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5565 entries, 0 to 5564
Data columns (total 74 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   ANO                                            5565 non-null   int64  
 1   UF                                             5565 non-null   object 
 2   Codmun7                                        5565 non-null   int64  
 3   Município                                      5565 non-null   object 
 4   expec_vida                                     5565 non-null   float64
 5   taxa_fecund                                    5565 non-null   float64
 6   MORT1                                          5565 non-null   float64
 7   %sobreviver_60a                                5565 non-null   float64
 8   taxa_envelh                                    5565 non-null   float64
 9   expec_anos_estudo_18                           5565 

In [150]:
idhmcovid.loc[pd.isnull(idhmcovid['last_available_confirmed_per_100k_inhabitants'])]

ANO  ... last_available_confirmed_per_100k_inhabitants
1086  2010  ...                                           NaN
2333  2010  ...                                           NaN
2355  2010  ...                                           NaN
2414  2010  ...                                           NaN
2819  2010  ...                                           NaN
2869  2010  ...                                           NaN
3007  2010  ...                                           NaN
3082  2010  ...                                           NaN
4717  2010  ...                                           NaN

[9 rows x 74 columns]

**Calculando média de coluna que serão utilizadas**

In [151]:
casosMedios = idhmcovid['last_available_confirmed_per_100k_inhabitants'].mean()
casosMedios = math.floor(casosMedios)

populacaoMedia = idhmcovid['estimated_population_2019'].mean()
populacaoMedia = math.floor(populacaoMedia)




**Trocando valores nulos pela média**

In [152]:
idhmcovid.update(idhmcovid['last_available_confirmed_per_100k_inhabitants'].fillna(casosMedios))
idhmcovid.update(idhmcovid['estimated_population_2019'].fillna(populacaoMedia))
idhmcovid.update(idhmcovid['city_ibge_code'].fillna(0))


In [153]:
idhmcovid.isnull().sum()

ANO                                              0
UF                                               0
Codmun7                                          0
Município                                        0
expec_vida                                       0
                                                ..
IDHM_L                                           0
IDHM_R                                           0
city_ibge_code                                   0
estimated_population_2019                        0
last_available_confirmed_per_100k_inhabitants    0
Length: 74, dtype: int64

**Juntando dados da mortalidade**

In [154]:
idhmcovid_wmort = pd.merge(base_mort, idhmcovid, left_on="ibgeID", right_on="city_ibge_code", how="left")

**Separando apenas as colunas necessárias para selecionar os previsores e a classe**

In [155]:
cols = list(idhmcovid.columns.values)
idhmcovid_classif = idhmcovid_wmort[['deaths_per_100k_inhabitants', 'expec_vida', 'taxa_fecund','MORT1','%sobreviver_60a','taxa_envelh','expec_anos_estudo_18','T_ANALF11A14','T_ANALF25M','T_ATRASO_0_BASICO','T_ATRASO_2_BASICO','T_FLPRE','T_FLSUPER','T_FREQSUPER1517','T_MED25M','T_SUPER25M','GINI','PIND','PINDCRI','PMPOB','PMPOBCRI','RDPC','CPR','EMP','P_AGRO','P_COM','P_CONSTR','P_EXTR','P_FORMAL','P_FUND','P_MED','P_SERV','P_SIUP','P_SUPER','T_DES2529','TRABCC','TRABPUB','TRABSC','T_AGUA','T_BANAGUA','T_DENS','T_LIXO','T_LUZ','AGUA_ESGOTO','PAREDE','T_CRIFUNDIN_TODOS','T_FORA4A5','T_FORA6A14','T_FUNDIN_TODOS','T_FUNDIN_TODOS_MMEIO','T_FUNDIN18MINF','T_M10A14CF','T_M15A17CF','T_MULCHEFEFIF014','T_NESTUDA_NTRAB_MMEIO','T_OCUPDESLOC_1','T_RMAXIDOSO','T_SLUZ','HOMEMTOT','MULHERTOT','pesoRUR','pesotot','pesourb','POP','IDHM','IDHM_E','IDHM_L','IDHM_R','estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants']]
idhmcovid_classif.head()

deaths_per_100k_inhabitants  ...  last_available_confirmed_per_100k_inhabitants
0                     79.79027  ...                                     6086.85740
1                     14.30820  ...                                     1230.50508
2                     54.88474  ...                                      633.66929
3                     71.02183  ...                                     2018.41495
4                      8.60696  ...                                      223.78104

[5 rows x 70 columns]

In [159]:
idhmcovid_classif.fillna(0,inplace=True)


/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


In [160]:
idhmcovid_classif.isnull().sum()

deaths_per_100k_inhabitants                      0
expec_vida                                       0
taxa_fecund                                      0
MORT1                                            0
%sobreviver_60a                                  0
                                                ..
IDHM_E                                           0
IDHM_L                                           0
IDHM_R                                           0
estimated_population_2019                        0
last_available_confirmed_per_100k_inhabitants    0
Length: 70, dtype: int64

**Lembrete para testes de exportação de CSV**

In [19]:
#idhmcovid_classif.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid_class.csv', index = False, header=True)
#idhmcovid.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid.csv', index = False, header=True)

**Separando previsores e classe**

In [250]:
previsores = idhmcovid_classif.iloc[:, 1:69]
classe_incid = idhmcovid_classif.iloc[:, 69].values
classe_mort = idhmcovid_classif.iloc[:, 0].values

**Transformação de atributos categóricos para numéricos**





In [ ]:
#from sklearn.preprocessing import LabelEncoder
#labelencoder = LabelEncoder()
#previsores.apply(LabelEncoder().fit_transform)

**Tratamento do dataframe de classe**

In [255]:
dataFrame = pd.DataFrame(data=classe_incid);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias_incid = dataFrame.niveis

In [256]:
dataFrame2 = pd.DataFrame(data=classe_mort);
dataFrame2.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame2.head()
categorias_mort = dataFrame2.niveis

In [232]:
categorias_incid = categorias_incid.values.reshape(-1, 1)
categorias_mort = categorias_mort.values.reshape(-1, 1)

**Visualização de quantos registros existem por classe**

In [233]:
unicos, quantidade = np.unique(categorias_incid, return_counts = True)
unicos

array([0.00000000e+00, 1.08436300e+01, 1.18497500e+01, ...,
       1.61887477e+04, 1.66403690e+04, 1.68099931e+04])

In [234]:
unicos2, quantidade2 = np.unique(categorias_mort, return_counts = True)
unicos2

array([0.0000000e+00, 3.2850000e-02, 6.9740000e-02, ..., 2.4958403e+02,
       2.7662517e+02, 3.3546813e+02])

**Agrupamento com k-means, utilizando 3 clusters**

In [235]:
cluster_inc = KMeans(n_clusters = 3)
cluster_inc.fit(categorias_incid)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [236]:
cluster_mort = KMeans(n_clusters = 3)
cluster_mort.fit(categorias_mort)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

**Visualização dos três centroides**

In [237]:
centroides_inc = cluster_inc.cluster_centers_
centroides_inc

array([[2747.40140811],
       [ 897.65401149],
       [6203.97343847]])

In [238]:
centroides_mort = cluster_mort.cluster_centers_
centroides_mort

array([[ 11.70005149],
       [106.26754856],
       [ 50.88111962]])

**Visualização dos grupos que cada registro foi associado** (Agrupamento)

In [239]:
previsoes = cluster_inc.labels_
previsoes

array([2, 1, 1, ..., 1, 0, 1], dtype=int32)

In [240]:
previsoes2 = cluster_mort.labels_
previsoes2

array([1, 0, 2, ..., 0, 1, 0], dtype=int32)

In [257]:
dataFrame = pd.DataFrame(data=previsoes);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias_incid = dataFrame.niveis

In [258]:
dataFrame2 = pd.DataFrame(data=previsoes2);
dataFrame2.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame2.head()
categorias_mort = dataFrame2.niveis

**Contagem dos registros por classe**

In [241]:
unicos_inc, quantidade_inc = np.unique(previsoes, return_counts = True)
unicos_inc

array([0, 1, 2], dtype=int32)

In [261]:
quantidade_inc

array([1695, 3579,  315])

In [259]:
categorias_incid

0       2
1       1
2       1
3       0
4       1
       ..
5584    1
5585    1
5586    1
5587    0
5588    1
Name: niveis, Length: 5589, dtype: int32

In [245]:
unicos_mort, quantidade_mort = np.unique(previsoes, return_counts = True)
unicos_mort

array([0, 1, 2], dtype=int32)

In [262]:
quantidade_mort

array([1695, 3579,  315])

In [260]:
categorias_mort

0       1
1       0
2       2
3       2
4       0
       ..
5584    0
5585    2
5586    0
5587    1
5588    0
Name: niveis, Length: 5589, dtype: int32

**Exportar csv de previsores e classe para os classificadores**

In [263]:
previsores.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/previsores.csv', index = False, header=True)
categorias_incid.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/classe_inc.csv', index = False, header=True)
categorias_mort.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/classe_inc.csv', index = False, header=True)
