<a href="https://colab.research.google.com/github/jorgewellison/classifiers-tcc/blob/main/Pre-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importação das bibliotecas**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

In [94]:
pd.set_option('display.max_rows', 300)

**Tratamento dos indicadores do IDHM**

In [3]:
atlas = pd.read_excel("/content/drive/My Drive/Colab Notebooks/covid-idhm/atlas2013_dadosbrutos_pt.xlsx", sheet_name=1, 
          usecols=['ANO', 'UF', 'Codmun7', 'Município', 'ESPVIDA', 'FECTOT', 'MORT1', 'SOBRE60', 'T_ENV', 'E_ANOSESTUDO', 'T_ANALF11A14', 'T_ANALF25M', 'T_ATRASO_0_BASICO', 'T_ATRASO_2_BASICO', 'T_FLPRE', 'T_FLSUPER', 'T_FREQSUPER1517', 'T_SUPER25M', 'T_MED25M', 'GINI', 'PIND', 'PINDCRI', 'PMPOB', 'PMPOBCRI', 'RDPC', 'CPR', 'EMP', 'P_AGRO', 'P_COM', 'P_CONSTR', 'P_EXTR', 'P_FORMAL', 'P_FUND', 'P_MED', 'P_SERV', 'P_SIUP', 'P_SUPER', 'T_DES2529', 'TRABCC', 'TRABPUB', 'TRABSC', 'T_AGUA', 'T_BANAGUA', 'T_DENS', 'T_LIXO', 'T_LUZ', 'AGUA_ESGOTO', 'PAREDE', 'T_CRIFUNDIN_TODOS', 'T_FORA4A5', 'T_FORA6A14', 'T_FUNDIN_TODOS', 'T_FUNDIN_TODOS_MMEIO', 'T_FUNDIN18MINF', 'T_M10A14CF', 'T_M15A17CF', 'T_MULCHEFEFIF014', 'T_NESTUDA_NTRAB_MMEIO', 'T_OCUPDESLOC_1', 'T_RMAXIDOSO', 'T_SLUZ', 'HOMEMTOT', 'MULHERTOT', 'pesoRUR', 'pesotot', 'pesourb', 'POP', 'IDHM', 'IDHM_E', 'IDHM_L', 'IDHM_R'], 
          dtype={'UF': str}).rename(columns={'ESPVIDA': 'expec_vida', 'FECTOT': 'taxa_fecund', 'SOBRE60': '%sobreviver_60a', 'T_ENV': 'taxa_envelh', 'E_ANOSESTUDO': 'expec_anos_estudo_18'})
atlasbr = atlas.loc[(atlas['ANO'] == 2010)]

In [ ]:
atlasbr.head()

ANO  UF  Codmun7              Município  ...   IDHM  IDHM_E  IDHM_L  IDHM_R
11130  2010  11  1100015  ALTA FLORESTA D'OESTE  ...  0.641   0.526   0.763   0.657
11131  2010  11  1100023              ARIQUEMES  ...  0.702   0.600   0.806   0.716
11132  2010  11  1100031                 CABIXI  ...  0.650   0.559   0.757   0.650
11133  2010  11  1100049                 CACOAL  ...  0.718   0.620   0.821   0.727
11134  2010  11  1100056             CEREJEIRAS  ...  0.692   0.602   0.799   0.688

[5 rows x 71 columns]

**Carregando dados de mortalidade e de mobilidade**

In [115]:
base_mort = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/cases-brazil-cities.csv", usecols=['ibgeID', 'deaths_per_100k_inhabitants'])
base_mort.head()

ibgeID  deaths_per_100k_inhabitants
0  5200050                     79.79027
1  3100104                     14.30820
2  5200100                     54.88474
3  1500107                     71.02183
4  3100203                      8.60696

In [28]:
mob = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/Social Distancing Index by Cities (1).csv", parse_dates = ['dt'])
mobbr = mob[['city_name', 'isolated', 'dt']]

In [29]:
mobbr

city_name  isolated         dt
0              Capivari do Sul  0.176474 2020-11-04
1                        Iperó  0.346263 2020-11-04
2                  Nova Europa  0.258624 2020-11-04
3        Campina Grande do Sul  0.305752 2020-11-04
4                      Camocim  0.392672 2020-11-04
...                        ...       ...        ...
1127908               Umarizal  0.321429 2020-02-01
1127909              Teolândia  0.238994 2020-02-01
1127910  Sebastião Laranjeiras  0.342466 2020-02-01
1127911               Roncador  0.339623 2020-02-01
1127912                 Gurupi  0.293558 2020-02-01

[1127913 rows x 3 columns]

In [31]:
mobbr.head()

city_name  isolated         dt
0        Capivari do Sul  0.176474 2020-11-04
1                  Iperó  0.346263 2020-11-04
2            Nova Europa  0.258624 2020-11-04
3  Campina Grande do Sul  0.305752 2020-11-04
4                Camocim  0.392672 2020-11-04

In [32]:
start_date  =  '2020-03-01'
mask = mobbr['dt'] >= start_date
mobbr_marco_novembro = mobbr.loc[mask]
mobbr_marco_novembro

city_name  isolated         dt
0                    Capivari do Sul  0.176474 2020-11-04
1                              Iperó  0.346263 2020-11-04
2                        Nova Europa  0.258624 2020-11-04
3              Campina Grande do Sul  0.305752 2020-11-04
4                            Camocim  0.392672 2020-11-04
...                              ...       ...        ...
1012573  Santo Antônio do Descoberto  0.402174 2020-03-01
1012574          Santa Luzia d'Oeste  0.320000 2020-03-01
1012575                 Águas Mornas  0.405660 2020-03-01
1012576                   Carutapera  0.360656 2020-03-01
1012577              Três Cachoeiras  0.445946 2020-03-01

[1012578 rows x 3 columns]

**Média durante toda a pandemia**

In [37]:
media_municipio = mobbr_marco_novembro.groupby('city_name')['isolated'].mean().reset_index(name='media_mes')
media_municipio

city_name  media_mes
0         Abadia de Goiás   0.362751
1     Abadia dos Dourados   0.420707
2               Abadiânia   0.388448
3              Abaetetuba   0.417864
4                  Abaeté   0.352498
...                   ...        ...
4554      Álvares Machado   0.385168
4555   Álvaro de Carvalho   0.383411
4556               Ângulo   0.361838
4557        Érico Cardoso   0.416686
4558               Óbidos   0.386262

[4559 rows x 2 columns]

**Adicionando dados de mobilidade e mortalidade aos dados da COVID-19**

In [107]:
base = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/covid19-setembro.csv") 

In [ ]:
base_mort = pd.merge(base_mort, base, left_on="ibgeID", right_on="city_ibge_code", how="left")
base_mort.isnull().sum()

In [129]:
base_mob = pd.merge(media_municipio, base_mort, left_on="city_name", right_on="city", how='left')
base_mob.head()

city_name  media_mes  ...  is_last  is_repeated
0      Abadia de Goiás   0.362751  ...     True        False
1  Abadia dos Dourados   0.420707  ...     True        False
2            Abadiânia   0.388448  ...     True        False
3           Abaetetuba   0.417864  ...    False        False
4               Abaeté   0.352498  ...     True        False

[5 rows x 52 columns]

In [130]:
base_mob.isnull().sum()

city_name                                           0
media_mes                                           0
ibgeID                                             62
deaths_per_100k_inhabitants                        62
epidemiological_week_x                             62
date_x                                             62
order_for_place_x                                  62
state_x                                            62
city_x                                             62
city_ibge_code_x                                   62
place_type_x                                       62
last_available_confirmed_x                         62
last_available_confirmed_per_100k_inhabitants_x    63
new_confirmed_x                                    62
last_available_deaths_x                            62
new_deaths_x                                       62
last_available_death_rate_x                        62
estimated_population_2019_x                        62
is_last_x                   

In [131]:
pd.isnull(base_mob['last_available_confirmed_per_100k_inhabitants'])
base_mob.loc[pd.isnull(base_mob['last_available_confirmed_per_100k_inhabitants'])]

city_name  media_mes  ...  is_last  is_repeated
88         Alta Floresta d'Oeste   0.432107  ...      NaN          NaN
130             Alvorada d'Oeste   0.432763  ...      NaN          NaN
131         Alvorada do Gurgueia   0.389974  ...      NaN          NaN
288                       Araçás   0.404736  ...      NaN          NaN
303                         Arez   0.419025  ...      NaN          NaN
334                         Assu   0.377513  ...      NaN          NaN
343              Atílio Vivácqua   0.378292  ...      NaN          NaN
412            Barra d'Alcântara   0.368507  ...      NaN          NaN
518               Biritiba Mirim   0.404515  ...      NaN          NaN
528                    Boa Saúde   0.408070  ...      NaN          NaN
544                     Bocaiuva   0.351799  ...      NaN          NaN
545              Bocaiuva do Sul   0.403180  ...      NaN          NaN
603                     Boraceia   0.407092  ...      NaN          NaN
612                    Botumirim   0.464488  ...      NaN          NaN
1105               Coité do Noia   0.409436  ...      NaN          NaN
1124         Colônia do Gurgueia   0.365631  ...      NaN          NaN
1142       Conceição do Lago Açu   0.433149  ...      NaN          NaN
1338                 Diamantina‎   0.424487  ...      NaN          NaN
1380                Dona Eusébia   0.421193  ...      NaN          NaN
1415        Eldorado dos Carajás   0.369451  ...      NaN          NaN
1446                       Ereré   0.418971  ...      NaN          NaN
1458             Espigão d'Oeste   0.441321  ...      NaN          NaN
1564        Fortaleza do Tabocão   0.335635  ...      NaN          NaN
1605                    Galileia   0.433407  ...      NaN          NaN
1688                   Grão-Pará   0.428840  ...      NaN          NaN
1742                    Guatambu   0.431344  ...      NaN          NaN
1943                     Ipuiuna   0.378288  ...      NaN          NaN
1989                      Itaetê   0.415324  ...      NaN          NaN
2043             Itapecuru-Mirim   0.351566  ...      NaN          NaN
2327           Lagedo do Tabocal   0.440837  ...      NaN          NaN
2380             Lambari d'Oeste   0.343087  ...      NaN          NaN
2386                    Laranjal   0.402991  ...    False         True
2394                Lauro Müller   0.416367  ...      NaN          NaN
2422                     Lindoia   0.392277  ...      NaN          NaN
2445                Luiz Antônio   0.393725  ...      NaN          NaN
2475          Machadinho d'Oeste   0.417987  ...      NaN          NaN
2495               Major Izidoro   0.409661  ...      NaN          NaN
2630                    Matureia   0.386050  ...      NaN          NaN
2799             Munhoz de Mello   0.406726  ...      NaN          NaN
2875    Nova Brasilândia d'Oeste   0.405958  ...      NaN          NaN
3146                Passa-e-Fica   0.346120  ...      NaN          NaN
3162                      Patos‎   0.394367  ...      NaN          NaN
3170                  Pau-d'Arco   0.435294  ...      NaN          NaN
3370                     Pompeia   0.375799  ...      NaN          NaN
3561        Redenção do Gurgueia   0.358636  ...      NaN          NaN
3710                    Rubineia   0.421272  ...      NaN          NaN
3821         Santa Luzia d'Oeste   0.405735  ...      NaN          NaN
3822       Santa Luzia do Itanhi   0.407849  ...      NaN          NaN
3897       Santana do Livramento   0.398542  ...      NaN          NaN
3926   Santo Antônio de Leverger   0.437344  ...      NaN          NaN
4111         São Bento do Trairi   0.398997  ...      NaN          NaN
4119                 São Caetano   0.383418  ...      NaN          NaN
4126        São Cristóvão do Sul   0.366440  ...      NaN          NaN
4182     São Gonçalo do Gurgueia   0.291373  ...      NaN          NaN
4269            São João del-Rei   0.423967  ...      NaN          NaN
4274            São João do Caru   0.370076  ..

In [132]:
base_mob = base_mob.drop([88,130,131,288,303,334,343,412,518,528,544,545,603,612,1105,1124,1142,1338,1380,1415,1446,1458,1564,1605,1688,1742,1943,1989,2043,2327,2380,2386,2394,2422,2445,2475,2495,2630,2799,2875,3146,3162,3170,3370,3561,3710,3821,3822,3897,3926,4111,4119,4126,4182,4269,4274,4332,4389,4390,4396,4426,4473,4715])

**Remodelando o dataframe dos casos de covid**

In [134]:
cols = list(base_mob.columns.values)
df = base_mob[['media_mes', 'city_ibge_code', 'estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants', 'deaths_per_100k_inhabitants']]
df.fillna(0,inplace=True)
df.isnull().sum()

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4327: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,


media_mes                                        0
city_ibge_code                                   0
estimated_population_2019                        0
last_available_confirmed_per_100k_inhabitants    0
deaths_per_100k_inhabitants                      0
dtype: int64

**Junção da tabela de métricas de indicadores do IDHM (Atlas) + dataFrame covid**

In [140]:
idhmcovid = pd.merge(atlasbr, df, left_on="Codmun7", right_on="city_ibge_code", how="left")
idhmcovid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5565 entries, 0 to 5564
Data columns (total 76 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   ANO                                            5565 non-null   int64  
 1   UF                                             5565 non-null   object 
 2   Codmun7                                        5565 non-null   int64  
 3   Município                                      5565 non-null   object 
 4   expec_vida                                     5565 non-null   float64
 5   taxa_fecund                                    5565 non-null   float64
 6   MORT1                                          5565 non-null   float64
 7   %sobreviver_60a                                5565 non-null   float64
 8   taxa_envelh                                    5565 non-null   float64
 9   expec_anos_estudo_18                           5565 

In [141]:
idhmcovid.loc[pd.isnull(idhmcovid['last_available_confirmed_per_100k_inhabitants'])]

ANO  ... deaths_per_100k_inhabitants
0     2010  ...                         NaN
2     2010  ...                         NaN
8     2010  ...                         NaN
12    2010  ...                         NaN
13    2010  ...                         NaN
...    ...  ...                         ...
5545  2010  ...                         NaN
5547  2010  ...                         NaN
5551  2010  ...                         NaN
5553  2010  ...                         NaN
5554  2010  ...                         NaN

[799 rows x 76 columns]

**Calculando média de coluna que serão utilizadas**

In [142]:
casosMedios = idhmcovid['last_available_confirmed_per_100k_inhabitants'].mean()
casosMedios = math.floor(casosMedios)

populacaoMedia = idhmcovid['estimated_population_2019'].mean()
populacaoMedia = math.floor(populacaoMedia)

media_mes = idhmcovid['media_mes'].mean()
media_mes = math.floor(media_mes)

mediaMortes = idhmcovid['deaths_per_100k_inhabitants'].mean()
mediaMortes = math.floor(mediaMortes)



**Trocando valores nulos pela média**

In [143]:
idhmcovid.update(idhmcovid['last_available_confirmed_per_100k_inhabitants'].fillna(casosMedios))
idhmcovid.update(idhmcovid['estimated_population_2019'].fillna(populacaoMedia))
idhmcovid.update(idhmcovid['media_mes'].fillna(media_mes))
idhmcovid.update(idhmcovid['deaths_per_100k_inhabitants'].fillna(mediaMortes))
idhmcovid.update(idhmcovid['city_ibge_code'].fillna(0))


In [144]:
idhmcovid.isnull().sum()

ANO                                              0
UF                                               0
Codmun7                                          0
Município                                        0
expec_vida                                       0
taxa_fecund                                      0
MORT1                                            0
%sobreviver_60a                                  0
taxa_envelh                                      0
expec_anos_estudo_18                             0
T_ANALF11A14                                     0
T_ANALF25M                                       0
T_ATRASO_0_BASICO                                0
T_ATRASO_2_BASICO                                0
T_FLPRE                                          0
T_FLSUPER                                        0
T_FREQSUPER1517                                  0
T_MED25M                                         0
T_SUPER25M                                       0
GINI                           

**Separando apenas as colunas necessárias para selecionar os previsores e a classe**

In [149]:
cols = list(idhmcovid.columns.values)
idhmcovid_classif = idhmcovid[['deaths_per_100k_inhabitants', 'media_mes', 'expec_vida', 'taxa_fecund','MORT1','%sobreviver_60a','taxa_envelh','expec_anos_estudo_18','T_ANALF11A14','T_ANALF25M','T_ATRASO_0_BASICO','T_ATRASO_2_BASICO','T_FLPRE','T_FLSUPER','T_FREQSUPER1517','T_MED25M','T_SUPER25M','GINI','PIND','PINDCRI','PMPOB','PMPOBCRI','RDPC','CPR','EMP','P_AGRO','P_COM','P_CONSTR','P_EXTR','P_FORMAL','P_FUND','P_MED','P_SERV','P_SIUP','P_SUPER','T_DES2529','TRABCC','TRABPUB','TRABSC','T_AGUA','T_BANAGUA','T_DENS','T_LIXO','T_LUZ','AGUA_ESGOTO','PAREDE','T_CRIFUNDIN_TODOS','T_FORA4A5','T_FORA6A14','T_FUNDIN_TODOS','T_FUNDIN_TODOS_MMEIO','T_FUNDIN18MINF','T_M10A14CF','T_M15A17CF','T_MULCHEFEFIF014','T_NESTUDA_NTRAB_MMEIO','T_OCUPDESLOC_1','T_RMAXIDOSO','T_SLUZ','HOMEMTOT','MULHERTOT','pesoRUR','pesotot','pesourb','POP','IDHM','IDHM_E','IDHM_L','IDHM_R','estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants']]
idhmcovid_classif.head()

deaths_per_100k_inhabitants  ...  last_available_confirmed_per_100k_inhabitants
0                     39.00000  ...                                     1813.00000
1                     86.22048  ...                                     4904.36943
2                     39.00000  ...                                     1813.00000
3                     39.83177  ...                                     2653.49875
4                     36.75795  ...                                     1519.32855

[5 rows x 71 columns]

In [151]:
idhmcovid_classif.head()

deaths_per_100k_inhabitants  ...  last_available_confirmed_per_100k_inhabitants
0                     39.00000  ...                                     1813.00000
1                     86.22048  ...                                     4904.36943
2                     39.00000  ...                                     1813.00000
3                     39.83177  ...                                     2653.49875
4                     36.75795  ...                                     1519.32855

[5 rows x 71 columns]

**Lembrete para testes de exportação de CSV**

In [ ]:
#idhmcovid_classif.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid_class.csv', index = False, header=True)
#idhmcovid.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid.csv', index = False, header=True)

**Separando previsores e classe**

In [153]:
previsores = idhmcovid_classif.iloc[:, 1:70]
classe_incid = idhmcovid_classif.iloc[:, 70].values
classe_mort = idhmcovid_classif.iloc[:, 0].values

**Transformação de atributos categóricos para numéricos**





In [ ]:
#from sklearn.preprocessing import LabelEncoder
#labelencoder = LabelEncoder()
#previsores.apply(LabelEncoder().fit_transform)

**Tratamento do dataframe de classe**

In [154]:
dataFrame = pd.DataFrame(data=classe_incid);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias_incid = dataFrame.niveis

In [155]:
dataFrame2 = pd.DataFrame(data=classe_mort);
dataFrame2.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame2.head()
categorias_mort = dataFrame2.niveis

In [156]:
categorias_incid = categorias_incid.values.reshape(-1, 1)
categorias_mort = categorias_mort.values.reshape(-1, 1)

**Visualização de quantos registros existem por classe**

In [157]:
unicos, quantidade = np.unique(categorias_incid, return_counts = True)
unicos

array([1.08436300e+01, 1.18497500e+01, 1.54966700e+01, ...,
       1.61887477e+04, 1.66403690e+04, 1.68099931e+04])

In [158]:
unicos2, quantidade2 = np.unique(categorias_mort, return_counts = True)
unicos2

array([  0.     ,   1.91421,   2.00698, ..., 229.73982, 233.00325,
       249.58403])

**Agrupamento com k-means, utilizando 3 clusters**

In [159]:
cluster_inc = KMeans(n_clusters = 3)
cluster_inc.fit(categorias_incid)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [160]:
cluster_mort = KMeans(n_clusters = 3)
cluster_mort.fit(categorias_mort)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

**Visualização dos três centroides**

In [166]:
centroides_inc = cluster_inc.cluster_centers_
centroides_inc

array([[2182.34548334],
       [5421.53425289],
       [ 798.43063429]])

In [167]:
centroides_mort = cluster_mort.cluster_centers_
centroides_mort

array([[11.86337725],
       [97.12017236],
       [44.26349611]])

**Visualização dos grupos que cada registro foi associado** (Agrupamento)

In [168]:
previsoes = cluster_inc.labels_
previsoes

array([0, 1, 0, ..., 2, 0, 1], dtype=int32)

In [169]:
previsoes2 = cluster_mort.labels_
previsoes2

array([2, 1, 2, ..., 0, 2, 1], dtype=int32)

In [170]:
dataFrame = pd.DataFrame(data=previsoes);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias_incid = dataFrame.niveis

In [171]:
dataFrame2 = pd.DataFrame(data=previsoes2);
dataFrame2.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame2.head()
categorias_mort = dataFrame2.niveis

**Contagem dos registros por classe**

In [172]:
unicos_inc, quantidade_inc = np.unique(previsoes, return_counts = True)
unicos_inc

array([0, 1, 2], dtype=int32)

In [173]:
quantidade_inc

array([2634,  431, 2500])

In [174]:
categorias_incid

0       0
1       1
2       0
3       0
4       0
       ..
5560    2
5561    0
5562    2
5563    0
5564    1
Name: niveis, Length: 5565, dtype: int32

In [175]:
unicos_mort, quantidade_mort = np.unique(previsoes, return_counts = True)
unicos_mort

array([0, 1, 2], dtype=int32)

In [176]:
quantidade_mort

array([2634,  431, 2500])

In [177]:
categorias_mort

0       2
1       1
2       2
3       2
4       2
       ..
5560    0
5561    2
5562    0
5563    2
5564    1
Name: niveis, Length: 5565, dtype: int32

**Exportar csv de previsores e classe para os classificadores**

In [ ]:
previsores.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/previsores.csv', index = False, header=True)
categorias_incid.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/classe_inc.csv', index = False, header=True)
categorias_mort.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/classe_mort.csv', index = False, header=True)
