<a href="https://colab.research.google.com/github/jorgewellison/classifiers-tcc/blob/main/Pre-processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importação das bibliotecas**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix

In [ ]:
pd.set_option('display.max_rows', 50)

**Tratamento dos indicadores do IDHM**

In [ ]:
atlas = pd.read_excel("/content/drive/My Drive/Colab Notebooks/covid-idhm/atlas2013_dadosbrutos_pt.xlsx", sheet_name=1, 
          usecols=['ANO', 'UF', 'Codmun7', 'Município', 'ESPVIDA', 'FECTOT', 'MORT1', 'SOBRE60', 'T_ENV', 'E_ANOSESTUDO', 'T_ANALF11A14', 'T_ANALF25M', 'T_ATRASO_0_BASICO', 'T_ATRASO_2_BASICO', 'T_FLPRE', 'T_FLSUPER', 'T_FREQSUPER1517', 'T_SUPER25M', 'T_MED25M', 'GINI', 'PIND', 'PINDCRI', 'PMPOB', 'PMPOBCRI', 'RDPC', 'CPR', 'EMP', 'P_AGRO', 'P_COM', 'P_CONSTR', 'P_EXTR', 'P_FORMAL', 'P_FUND', 'P_MED', 'P_SERV', 'P_SIUP', 'P_SUPER', 'T_DES2529', 'TRABCC', 'TRABPUB', 'TRABSC', 'T_AGUA', 'T_BANAGUA', 'T_DENS', 'T_LIXO', 'T_LUZ', 'AGUA_ESGOTO', 'PAREDE', 'T_CRIFUNDIN_TODOS', 'T_FORA4A5', 'T_FORA6A14', 'T_FUNDIN_TODOS', 'T_FUNDIN_TODOS_MMEIO', 'T_FUNDIN18MINF', 'T_M10A14CF', 'T_M15A17CF', 'T_MULCHEFEFIF014', 'T_NESTUDA_NTRAB_MMEIO', 'T_OCUPDESLOC_1', 'T_RMAXIDOSO', 'T_SLUZ', 'HOMEMTOT', 'MULHERTOT', 'pesoRUR', 'pesotot', 'pesourb', 'POP', 'IDHM', 'IDHM_E', 'IDHM_L', 'IDHM_R'], 
          dtype={'UF': str}).rename(columns={'ESPVIDA': 'expec_vida', 'FECTOT': 'taxa_fecund', 'SOBRE60': '%sobreviver_60a', 'T_ENV': 'taxa_envelh', 'E_ANOSESTUDO': 'expec_anos_estudo_18'})
atlasbr = atlas.loc[(atlas['ANO'] == 2010)]

In [ ]:
atlasbr.head()

ANO  UF  Codmun7              Município  ...   IDHM  IDHM_E  IDHM_L  IDHM_R
11130  2010  11  1100015  ALTA FLORESTA D'OESTE  ...  0.641   0.526   0.763   0.657
11131  2010  11  1100023              ARIQUEMES  ...  0.702   0.600   0.806   0.716
11132  2010  11  1100031                 CABIXI  ...  0.650   0.559   0.757   0.650
11133  2010  11  1100049                 CACOAL  ...  0.718   0.620   0.821   0.727
11134  2010  11  1100056             CEREJEIRAS  ...  0.692   0.602   0.799   0.688

[5 rows x 71 columns]

**Substituição dos valores nulos**

In [ ]:
base = pd.read_csv("/content/drive/My Drive/Colab Notebooks/covid-idhm/covid19-setembro.csv") 
base.head()

epidemiological_week        date  ...  is_last is_repeated
0                    40  2020-09-27  ...    False        True
1                    40  2020-09-27  ...    False        True
2                    40  2020-09-27  ...    False        True
3                    40  2020-09-27  ...    False        True
4                    40  2020-09-27  ...    False        True

[5 rows x 16 columns]

In [ ]:
base.isnull().sum()

epidemiological_week                              0
date                                              0
order_for_place                                   0
state                                             0
city                                              0
city_ibge_code                                   19
place_type                                        0
last_available_confirmed                          0
last_available_confirmed_per_100k_inhabitants    22
new_confirmed                                     0
last_available_deaths                             0
new_deaths                                        0
last_available_death_rate                         0
estimated_population_2019                        19
is_last                                           0
is_repeated                                       0
dtype: int64

In [ ]:
pd.isnull(base['last_available_confirmed_per_100k_inhabitants'])
base.loc[pd.isnull(base['last_available_confirmed_per_100k_inhabitants'])]

epidemiological_week        date  ...  is_last is_repeated
57                      40  2020-09-27  ...    False        True
367                     40  2020-09-27  ...    False       False
698                     40  2020-09-27  ...    False       False
807                     40  2020-09-27  ...     True       False
841                     40  2020-09-27  ...    False        True
994                     40  2020-09-27  ...     True       False
1695                    40  2020-09-27  ...     True       False
2326                    40  2020-09-27  ...    False        True
2473                    40  2020-09-27  ...    False       False
2650                    40  2020-09-27  ...    False       False
2865                    40  2020-09-27  ...     True       False
3346                    40  2020-09-27  ...    False        True
3384                    40  2020-09-27  ...    False        True
3626                    40  2020-09-27  ...    False        True
3740                    40  2020-09-27  ...    False        True
3879                    40  2020-09-27  ...    False        True
3918                    40  2020-09-27  ...    False        True
4025                    40  2020-09-27  ...     True       False
4100                    40  2020-09-27  ...     True       False
4131                    40  2020-09-27  ...     True       False
4539                    40  2020-09-27  ...    False        True
5032                    40  2020-09-27  ...    False        True

[22 rows x 16 columns]

In [ ]:
base = base.drop([57, 367, 698, 807, 841, 994, 1695, 2326, 2473, 2650, 2865, 3346, 3626, 3740, 3879, 3918, 4131, 4539, 5032])

**Remodelando o dataframe dos casos de covid**

In [ ]:
cols = list(base.columns.values)
df = base[['city_ibge_code', 'estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants']]
df.fillna(0,inplace=True)
df.isnull().sum()

**Junção da tabela de métricas de indicadores do IDHM (Atlas) + dataFrame covid**

In [ ]:
idhmcovid = pd.merge(atlasbr, df, left_on="Codmun7", right_on="city_ibge_code", how="left")
idhmcovid.info()

In [ ]:
idhmcovid.loc[pd.isnull(idhmcovid['last_available_confirmed_per_100k_inhabitants'])]

ANO  ... last_available_confirmed_per_100k_inhabitants
1086  2010  ...                                           NaN
2333  2010  ...                                           NaN
2355  2010  ...                                           NaN
2414  2010  ...                                           NaN
2819  2010  ...                                           NaN
2869  2010  ...                                           NaN
3007  2010  ...                                           NaN
3082  2010  ...                                           NaN
4717  2010  ...                                           NaN

[9 rows x 74 columns]

**Calculando média de coluna que serão utilizadas**

In [ ]:
casosMedios = idhmcovid['last_available_confirmed_per_100k_inhabitants'].mean()
casosMedios = math.floor(casosMedios)

populacaoMedia = idhmcovid['estimated_population_2019'].mean()
populacaoMedia = math.floor(populacaoMedia)




**Trocando valores nulos pela média**

In [ ]:
idhmcovid.update(idhmcovid['last_available_confirmed_per_100k_inhabitants'].fillna(casosMedios))
idhmcovid.update(idhmcovid['estimated_population_2019'].fillna(populacaoMedia))
idhmcovid.update(idhmcovid['city_ibge_code'].fillna(0))


In [ ]:
idhmcovid.isnull().sum()

ANO                                              0
UF                                               0
Codmun7                                          0
Município                                        0
expec_vida                                       0
                                                ..
IDHM_L                                           0
IDHM_R                                           0
city_ibge_code                                   0
estimated_population_2019                        0
last_available_confirmed_per_100k_inhabitants    0
Length: 74, dtype: int64

**Separando apenas as colunas necessárias para selecionar os previsores e a classe**

In [ ]:
cols = list(idhmcovid.columns.values)
idhmcovid_classif = idhmcovid[['expec_vida', 'taxa_fecund','MORT1','%sobreviver_60a','taxa_envelh','expec_anos_estudo_18','T_ANALF11A14','T_ANALF25M','T_ATRASO_0_BASICO','T_ATRASO_2_BASICO','T_FLPRE','T_FLSUPER','T_FREQSUPER1517','T_MED25M','T_SUPER25M','GINI','PIND','PINDCRI','PMPOB','PMPOBCRI','RDPC','CPR','EMP','P_AGRO','P_COM','P_CONSTR','P_EXTR','P_FORMAL','P_FUND','P_MED','P_SERV','P_SIUP','P_SUPER','T_DES2529','TRABCC','TRABPUB','TRABSC','T_AGUA','T_BANAGUA','T_DENS','T_LIXO','T_LUZ','AGUA_ESGOTO','PAREDE','T_CRIFUNDIN_TODOS','T_FORA4A5','T_FORA6A14','T_FUNDIN_TODOS','T_FUNDIN_TODOS_MMEIO','T_FUNDIN18MINF','T_M10A14CF','T_M15A17CF','T_MULCHEFEFIF014','T_NESTUDA_NTRAB_MMEIO','T_OCUPDESLOC_1','T_RMAXIDOSO','T_SLUZ','HOMEMTOT','MULHERTOT','pesoRUR','pesotot','pesourb','POP','IDHM','IDHM_E','IDHM_L','IDHM_R','estimated_population_2019', 'last_available_confirmed_per_100k_inhabitants']]

**Lembrete para testes de exportação de CSV**

In [ ]:
#idhmcovid_classif.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid_class.csv', index = False, header=True)
#idhmcovid.to_csv (r'C:\Users\Jorge\Documents\TCC\idhm-pb-master\idhmcovid.csv', index = False, header=True)

**Separando previsores e classe**

In [ ]:
previsores = idhmcovid_classif.iloc[:, 0:68]
classe = idhmcovid_classif.iloc[:, 68].values

**Transformação de atributos categóricos para numéricos**





In [ ]:
#from sklearn.preprocessing import LabelEncoder
#labelencoder = LabelEncoder()
#previsores.apply(LabelEncoder().fit_transform)
Não é necessário mais, os atributos são todos numéricos.

**Tratamento do dataframe de classe**

In [ ]:
dataFrame = pd.DataFrame(data=classe);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias = dataFrame.niveis

In [ ]:
categorias = categorias.values.reshape(-1, 1)

**Visualização de quantos registros existem por classe**

In [ ]:
unicos, quantidade = np.unique(categorias, return_counts = True)
unicos

array([0.00000000e+00, 1.08436300e+01, 1.18497500e+01, ...,
       1.61887477e+04, 1.66403690e+04, 1.68099931e+04])

**Agrupamento com k-means, utilizando 3 clusters**

In [ ]:
cluster = KMeans(n_clusters = 3)
cluster.fit(categorias)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

**Visualização dos três centroides**

In [ ]:
centroides = cluster.cluster_centers_
centroides

array([[ 915.91007814],
       [2763.89516239],
       [6203.97343847]])

**Visualização dos grupos que cada registro foi associado** (Agrupamento)

In [ ]:
previsoes = cluster.labels_
previsoes

array([1, 2, 1, ..., 0, 1, 2], dtype=int32)

In [ ]:
dataFrame = pd.DataFrame(data=previsoes);
dataFrame.rename(columns = {0: 'niveis'}, inplace=True)
dataFrame.head()
categorias = dataFrame.niveis

**Contagem dos registros por classe**

In [ ]:
unicos2, quantidade2 = np.unique(previsoes, return_counts = True)
unicos2

array([0, 1, 2], dtype=int32)

In [ ]:
quantidade2

array([3584, 1667,  314])

In [ ]:
categorias

0       1
1       2
2       1
3       1
4       0
       ..
5560    0
5561    0
5562    0
5563    1
5564    2
Name: niveis, Length: 5565, dtype: int32

**Exportar csv de previsores e classe para os classificadores**

In [ ]:
previsores.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/previsores.csv', index = False, header=True)
categorias.to_csv (r'/content/drive/My Drive/Colab Notebooks/covid-idhm/classe.csv', index = False, header=True)


**Cálculo de níveis de incidência do COVID**

In [ ]:
#categorias = pd.qcut(q, 3, labels=['baixa', 'moderada', 'alta'])
#categorias

0           alta
1           alta
2       moderada
3           alta
4       moderada
          ...   
5560    moderada
5561    moderada
5562       baixa
5563        alta
5564        alta
Name: niveis, Length: 5565, dtype: category
Categories (3, object): [baixa < moderada < alta]